-- Create reports table (if it doesn't exist already)
-- This matches your existing schema
CREATE TABLE IF NOT EXISTS reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  address TEXT,
  note TEXT,
  inserted_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- Create index on inserted_at for faster sorting
CREATE INDEX IF NOT EXISTS idx_reports_inserted_at ON reports(inserted_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations for now
-- You can modify this later to restrict based on user authentication
CREATE POLICY "Allow all operations on reports"
  ON reports
  FOR ALL
  USING (true)
  WITH CHECK (true);
